export default [{
    name: 'Autumn Carry',
    tagline: 'Order Online for',
    price: '$420',
    image: require('../../assets/foods/meal-carry.jpeg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Fish-Carry',
    tagline: 'Order Online for',
    price: '$399',
    image: require('../../assets/foods/fish-carry.jpeg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'EggItem',
    tagline: 'Order Online for',
    price: '$400',
    image: require('../../assets/foods/EggItem.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Meal with Noodles',
    tagline: 'Order Online for',
    price: '$220',
    image: require('../../assets/foods/noodles.jpeg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Little Bowl',
    tagline: 'Order Online for',
    price: '$320',
    image: require('../../assets/foods/oil-meal.jpeg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Pizza',
    tagline: 'Order Online for',
    price: '$350',
    image: require('../../assets/foods/pijja.jpeg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Pancake Stack',
    tagline: 'Order Online for',
    price: '$320',
    image: require('../../assets/foods/set-item.jpeg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Vegetable Items',
    tagline: 'Order Online for',
    price: '$450',
    image: require('../../assets/foods/vegitablsItems.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Yogurt Bowl',
    tagline: 'Order Online for',
    price: '$550',
    image: require('../../assets/foods/setMeals.jpeg.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}];