export default [{
    name: 'Autumn Soup',
    tagline: 'Order Online for',
    price: '$420',
    image: require('../../assets/foods/Autumn Soup.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Chicken Sandwich',
    tagline: 'Order Online for',
    price: '$399',
    image: require('../../assets/foods/Chicken Sandwich.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'EggItem',
    tagline: 'Order Online for',
    price: '$400',
    image: require('../../assets/foods/EggItem.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Meal with salmon and zucchini',
    tagline: 'Order Online for',
    price: '$220',
    image: require('../../assets/foods/Meal with salmon and zucchini.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Little Bowl',
    tagline: 'Order Online for',
    price: '$320',
    image: require('../../assets/foods/little bowl.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Mediterranean Salad',
    tagline: 'Order Online for',
    price: '$350',
    image: require('../../assets/foods/Mediterranean Salad.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Pancake Stack',
    tagline: 'Order Online for',
    price: '$320',
    image: require('../../assets/foods/Pancake Stack.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Vegetable Items',
    tagline: 'Order Online for',
    price: '$450',
    image: require('../../assets/foods/vegitablsItems.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}, {
    name: 'Yogurt Bowl',
    tagline: 'Order Online for',
    price: '$550',
    image: require('../../assets/foods/Yogurt Bowl.jpg'),
    description: ' If you use this site regularly and would like to help keep the site on the Internet, please consider donating a small sum to help pay for the hosting and bandwidth bill. There is no minimum donation, any sum is appreciated',
}];